const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const W=canvas.width,H=canvas.height,GROUND=454,GRAVITY=.72;
const coinsEl=document.querySelector('#coins'),ammoEl=document.querySelector('#ammo'),livesEl=document.querySelector('#lives'),levelEl=document.querySelector('#level'),timeEl=document.querySelector('#time');
const overlay=document.querySelector('#overlay'),startButton=document.querySelector('#start'),musicFrame=document.querySelector('#music-player'),shotFrame=document.querySelector('#shot-player'),musicToggle=document.querySelector('#music-toggle');
const keys={},enemyImage=new Image(),heroImage=new Image(); enemyImage.src='shou-tucker.png';heroImage.src='jorge.png';
let player,enemies,bullets,score,ammo,reload,lives,round,time,running,last,timerId,musicStarted=false,musicMuted=false,shotLoaded=false,shotPlaying=false;

function startMusic(){if(!musicStarted){musicFrame.src='https://www.youtube-nocookie.com/embed/qUpYdzlKHH8?autoplay=1&loop=1&playlist=qUpYdzlKHH8&enablejsapi=1&controls=0&rel=0';musicStarted=true}else sendMusic('playVideo');}
function sendMusic(command){musicFrame.contentWindow?.postMessage(JSON.stringify({event:'command',func:command,args:''}),'*');}
function loadShotSound(){if(!shotLoaded){shotFrame.src='https://www.youtube-nocookie.com/embed/XLUSqtqHxXc?enablejsapi=1&controls=0&rel=0';shotLoaded=true;}}
function playShotSound(){if(shotPlaying)return;if(!shotLoaded){loadShotSound();shotFrame.onload=()=>playShotSound();return;}shotPlaying=true;shotFrame.contentWindow?.postMessage(JSON.stringify({event:'command',func:'seekTo',args:[0,true]}),'*');shotFrame.contentWindow?.postMessage(JSON.stringify({event:'command',func:'playVideo',args:''}),'*');}
function updateHud(){coinsEl.textContent=String(score).padStart(2,'0');ammoEl.textContent=reload>0?'REC.':`${ammo}/30`;livesEl.textContent=String(lives).padStart(2,'0');levelEl.textContent=String(round).padStart(2,'0');timeEl.textContent=String(Math.max(0,time)).padStart(3,'0');}
function hit(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;}
function loadRound(){player={x:W/2-19,y:GROUND-50,w:38,h:50,vx:0,vy:0,grounded:true,facing:1,attack:0,invul:0};ammo=30;reload=0;bullets=[];enemies=[];const total=8+round*5,health=2+Math.floor((round-1)/2);for(let i=0;i<total;i++){const left=i%2===0;const speed=1.65+Math.random()*1.2+round*.16;enemies.push({x:left?-45:W+45,y:GROUND-34,w:38,h:34,vx:left?speed:-speed,vy:0,stun:30+Math.random()*80,grounded:true,dodge:0,hp:health,maxHp:health});}updateHud();}
function startGame(){startMusic();loadShotSound();score=0;lives=3;round=1;time=120;running=true;last=performance.now();overlay.classList.add('hidden');loadRound();clearInterval(timerId);timerId=setInterval(()=>{if(running){time--;if(time<=0)end('¡Se acabó el tiempo!');updateHud();}},1000);requestAnimationFrame(loop);}
function end(text){running=false;clearInterval(timerId);overlay.innerHTML=`<div class="card"><p class="eyebrow">FIN DEL JUEGO</p><h1>${text}</h1><p>Ronda alcanzada: ${round}<br>Enemigos eliminados: ${score}</p><button id="start">JUGAR DE NUEVO</button></div>`;overlay.classList.remove('hidden');document.querySelector('#start').onclick=startGame;}
function fire(){if(ammo<=0||reload>0)return;const p=player;ammo--;if(ammo===0)reload=80;p.attack=8;playShotSound();bullets.push({x:p.facing>0?p.x+p.w:p.x-15,y:p.y+21,w:17,h:7,vx:p.facing*11,life:58});updateHud();}
function hurt(){if(player.invul>0)return;lives--;updateHud();if(lives<=0)return end('Jorge no sobrevivió a la ronda.');player.x=W/2-player.w/2;player.y=GROUND-player.h;player.vx=player.vy=0;player.invul=85;enemies.forEach(e=>e.stun=55);}
function update(){const p=player,move=(keys.ArrowRight||keys.KeyD?1:0)-(keys.ArrowLeft||keys.KeyA?1:0);p.vx+=move*.76;if(move)p.facing=move;p.vx*=.78;p.vx=Math.max(-6,Math.min(6,p.vx));if((keys.Space||keys.ArrowUp||keys.KeyW)&&p.grounded){p.vy=-13;p.grounded=false;keys.Space=keys.ArrowUp=keys.KeyW=false;}if(keys.KeyF&&p.attack<=0){keys.KeyF=false;fire();}if(p.attack>0)p.attack--;if(p.invul>0)p.invul--;if(reload>0&&--reload===0){ammo=30;updateHud();}p.vy+=GRAVITY;p.x=Math.max(0,Math.min(W-p.w,p.x+p.vx));p.y+=p.vy;if(p.y+p.h>=GROUND){p.y=GROUND-p.h;p.vy=0;p.grounded=true;}
bullets=bullets.filter(b=>{b.x+=b.vx;b.life--;return b.life>0&&b.x>-20&&b.x<W+20;});
enemies.forEach(e=>{if(e.stun>0){e.stun--;return;}if(e.dodge>0)e.dodge--;const incoming=bullets.find(b=>Math.abs(b.y-(e.y+e.h/2))<32&&Math.abs(b.x-(e.x+e.w/2))<185&&Math.sign(b.vx)===Math.sign((e.x+e.w/2)-b.x));if(incoming&&e.grounded&&e.dodge<=0&&Math.random()<Math.min(.28+round*.055,.82)){e.vy=-(8+Math.min(round*.18,3));e.grounded=false;e.dodge=38;}const toward=Math.sign((p.x+p.w/2)-(e.x+e.w/2));const maxSpeed=3.4+round*.34;e.vx+=toward*(.12+round*.018);e.vx=Math.max(-maxSpeed,Math.min(maxSpeed,e.vx));e.vx*=.977;e.vy+=GRAVITY;e.x+=e.vx;e.y+=e.vy;e.grounded=false;if(e.y+e.h>=GROUND){e.y=GROUND-e.h;e.vy=0;e.grounded=true;}if(e.x<0||e.x+e.w>W)e.vx*=-1;for(const b of bullets)if(hit(b,e)){e.hp--;b.life=0;if(e.hp<=0){e.dead=true;score++;}}if(!e.dead&&!p.invul&&hit(p,e))hurt();});enemies=enemies.filter(e=>!e.dead);if(!enemies.length){round++;time+=15;loadRound();}}
function cloud(x,y,s){ctx.fillStyle='#ffffffa8';ctx.beginPath();[[0,12,15],[18,2,21],[43,10,15],[58,16,12]].forEach(([dx,dy,r])=>{ctx.moveTo(x+dx+r*s,y+dy*s);ctx.arc(x+dx*s,y+dy*s,r*s,0,Math.PI*2)});ctx.fill();}
function draw(){const sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#513ca4');sky.addColorStop(1,'#e9b9a6');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);cloud(90,85,1.2);cloud(600,130,1);ctx.fillStyle='#54403c';ctx.fillRect(0,GROUND,W,H-GROUND);ctx.fillStyle='#7cbf53';ctx.fillRect(0,GROUND,W,13);ctx.fillStyle='#9b7048';for(let x=0;x<W;x+=32)ctx.fillRect(x,GROUND+26,16,7);
ctx.fillStyle='#f9dd53';bullets.forEach(b=>{ctx.fillRect(b.x,b.y,b.w,b.h);ctx.fillStyle='#fff4b7';ctx.fillRect(b.x+4,b.y+1,8,3);ctx.fillStyle='#f9dd53';});
enemies.forEach(e=>{ctx.save();ctx.beginPath();ctx.roundRect(e.x,e.y,e.w,e.h,8);ctx.clip();if(enemyImage.complete)ctx.drawImage(enemyImage,115,0,520,350,e.x,e.y,e.w,e.h);else{ctx.fillStyle='#81566e';ctx.fillRect(e.x,e.y,e.w,e.h);}ctx.restore();ctx.strokeStyle='#38213b';ctx.lineWidth=2;ctx.strokeRect(e.x,e.y,e.w,e.h);ctx.fillStyle='#2d2535';ctx.fillRect(e.x,e.y-8,e.w,5);ctx.fillStyle='#ef4e51';ctx.fillRect(e.x,e.y-8,e.w*(e.hp/e.maxHp),5);});
const p=player;ctx.save();ctx.translate(p.x+p.w/2,p.y);ctx.scale(p.facing,1);ctx.beginPath();ctx.roundRect(-19,0,38,50,7);ctx.clip();if(heroImage.complete)ctx.drawImage(heroImage,0,0,heroImage.naturalWidth,heroImage.naturalHeight,-19,0,38,50);else{ctx.fillStyle='#df5d4e';ctx.fillRect(-16,7,32,31);}ctx.restore();ctx.strokeStyle='#30283a';ctx.lineWidth=2;ctx.strokeRect(p.x,p.y,p.w,p.h);if(p.attack>0){ctx.save();ctx.translate(p.x+p.w/2,p.y);ctx.scale(p.facing,1);ctx.fillStyle='#f0b453';ctx.fillRect(15,20,20,12);ctx.restore();}}
function loop(now){if(!running)return;if(now-last>11){update();draw();last=now;}requestAnimationFrame(loop);}
addEventListener('message',e=>{if(!e.origin.includes('youtube'))return;try{const data=typeof e.data==='string'?JSON.parse(e.data):e.data;if(data.event==='onStateChange'&&data.info===0)shotPlaying=false;}catch{}});
addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','Space','KeyA','KeyD','KeyW','KeyF'].includes(e.code)){e.preventDefault();keys[e.code]=true;}});addEventListener('keyup',e=>keys[e.code]=false);
document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;['pointerdown','pointerup','pointercancel','pointerleave'].forEach(type=>b.addEventListener(type,e=>{e.preventDefault();keys[k]=type==='pointerdown';}));});
musicToggle.onclick=()=>{musicMuted=!musicMuted;sendMusic(musicMuted?'mute':'unMute');musicToggle.textContent=musicMuted?'♫ Música apagada':'♫ Música';};startButton.onclick=startGame;round=1;loadRound();draw();
